[package]
name = "websocat"
version = "0.5.1-alpha"
authors = ["Vitaly \"_Vi\" Shukela <vi0oss@gmail.com>"]
license = "MIT"
repository = "https://github.com/vi/websocat"
description = "Connection forwarder from/to web sockets to/from usual sockets, in style of socat"
keywords = ["WebSocket", "socat", "rfc6455", "netcat", "tunnel"]
exclude = ["autorelease.sh"]


[dependencies]
websocket = { version = "0.20", default-features = false, features=["async"] }
#env_logger = {version="*", default-features = false }
#log = {version="*", default-features = false}
#url = { version="*" }
#clap = { version = "*", default-features = false }
futures = "0.1"
tokio-core = "0.1.12"
tokio-io = "0.1.6"
tokio-stdin-stdout = "0.1"

[target.'cfg(unix)'.dependencies]
tokio-file-unix = "^0.4.2"
tokio-signal = { version = "0.1", optional = true }

[features]
default = ["signal_handler"]
no_unix_stdio = []
ssl = ["websocket/async-ssl"]
signal_handler = ["tokio-signal"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
