[package]
name = "websocat"
version = "1.0.0"
authors = ["Vitaly \"_Vi\" Shukela <vi0oss@gmail.com>"]
license = "MIT"
repository = "https://github.com/vi/websocat"
description = "Command-line client for web sockets, like netcat/curl/socat for ws://."
keywords = ["WebSocket", "socat", "rfc6455", "netcat", "tunnel", "cli"]
exclude = ["autorelease.sh"]
readme = "README.md"


[dependencies]
websocket = { version = "0.20.2", default-features = false, features=["async"] }
env_logger = {version="0.5.9", default-features = false }
log = {version="0.4.1", default-features = false}
futures = {version = "=0.1.17" }
tokio-core =  { version = "=0.1.12" }
tokio-io = "=0.1.5"
tokio-stdin-stdout = "0.1.3"
structopt = { version = "0.2", default-features = false }
tokio-process = {version = "0.1.5" , optional = true }
slab_typesafe = "0.1"
hyper="0.10.13"
openssl-probe = { version = "0.1.2", optional = true }
smart-default = "0.2.0"


[target.'cfg(unix)'.dependencies]
tokio-file-unix = "^0.4.2"
tokio-signal = { version = "0.1", optional = true }
tokio-uds = "=0.1.5"
libc = { version = "0.2", optional = true }

[features]
default = ["signal_handler", "tokio-process", "unix_stdio"]
unix_stdio = []
ssl = ["websocket/async-ssl"]
signal_handler = ["tokio-signal"]
workaround1=["libc"]
seqpacket=["libc"]

[replace]
#"tokio-process:0.1.6" = {path="/mnt/src/git/tokio-process"}
#"tokio-core:0.1.12" = {path="/mnt/src/git/tokio-core"}

[dev-dependencies]
tokio-timer = "=0.1.2"

[profile.release]
opt-level = 2
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'

[package.metadata.deb]
section = "utility"
extended-description = """\
A tool allows you to interconnect two specifiers, like in socat, \
but with Websocket and some other additional functions."""
features = ["ssl", "workaround1", "seqpacket", "unix_stdio"]
#depends = "$auto"
depends = "libssl1.1, libc6 (>= 2.19), libgcc1 (>= 1:4.9.0)"
