[package]
name = "websocat"
version = "1.0.0-alpha"
authors = ["Vitaly \"_Vi\" Shukela <vi0oss@gmail.com>"]
license = "MIT"
repository = "https://github.com/vi/websocat"
description = "Connection forwarder from/to web sockets to/from usual sockets, in style of socat"
keywords = ["WebSocket", "socat", "rfc6455", "netcat", "tunnel"]
exclude = ["autorelease.sh"]


[dependencies]
websocket = { version = "0.20.2", default-features = false, features=["async"] }
env_logger = {version="0.5.9", default-features = false }
log = {version="0.4.1", default-features = false}
#clap = { version = "*", default-features = false }
futures = {version = "=0.1.17" }
tokio-core =  { version = "=0.1.12" }
tokio-io = "=0.1.5"
tokio-stdin-stdout = "0.1.1"
structopt = { version = "0.2", default-features = false }
tokio-process = {version = "0.1.5" , optional = true }


[target.'cfg(unix)'.dependencies]
tokio-file-unix = "^0.4.2"
tokio-signal = { version = "0.1", optional = true }
tokio-uds = "=0.1.5"
libc = { version = "0.2", optional = true }

[features]
default = ["signal_handler", "tokio-process"]
no_unix_stdio = []
ssl = ["websocket/async-ssl"]
signal_handler = ["tokio-signal"]
workaround1=["libc"]
#seqpacket=["libc"]

[dev-dependencies]
tokio-timer = "=0.1.2"

[profile.release]
opt-level = 2
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
