[package]
name = "websocat"
version = "0.3.0"
authors = ["Vitaly \"_Vi\" Shukela <vi0oss@gmail.com>"]
license = "MIT"
repository = "https://github.com/vi/websocat"
description = "Connection forwarder from/to web sockets to/from usual sockets, in style of socat"
keywords = ["WebSocket", "socat", "rfc6455", "netcat", "tunnel"]
exclude = ["autorelease.sh"]


[dependencies]
websocket = { git = "file:///mnt/src/git/rust-websocket/.git", rev="3d572357b9b62457478ca330fac244b6dc9d06c7", default-features = true }
env_logger = {version="^0.3.5", default-features = false }
log = {version="^0.3.5", default-features = false}
error-chain = {version="^0.6.1"}
url = { version="^1.2.3" }
clap = { version = "^2.18", default-features = false }
unix_socket = { version = "~0.5", optional = true }

[features]
unix_websockets = ["unix_socket"]
